name: CI
on:
  push:
  workflow_dispatch:
jobs:
  shell:
      runs-on: ubuntu-latest
      steps:
      - uses: omahn/wireguard-ssh-github-action@v1.4
        with:
          # Required. IP address of your WireGuard peer/endpoint. Must be publicly reachable.
          peer_ip: '${{ secrets.ip }}'
          # Required. SSH public key as a string.
          ssh_public_key: '${{ secrets.key }}'
          # Port of WireGuard peer.
          peer_port: '51820'
          # Private IP of GitHub WireGuard peer.
          github_ip: '192.168.192.1'
          # Seconds to wait for SSH connection.
          ssh_connection_timeout: '300'
          # Seconds to timeout SSH session.
          session_timeout: 3600
