name: CI
on:
  push:
  workflow_dispatch:
jobs:
  shell:
      runs-on: ubuntu-latest
      steps:
        - name: ssh
          run: |
            sudo systemctl start sshd
            ssh localhost
