name: CI

on:
  push:

jobs:
  build-linux:
    name: build-${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - aarch64-linux-android
        include:
          - target: aarch64-unknown-linux-musl
            use-cross: true

          - target: aarch64-linux-android
            use-cross: true
  shell:
      runs-on: ubuntu-latest
      steps:
        - name: test env and gh and curl and jq
          env:
            UPSTREAM_FULL_NAME: $(gh api repos/${GITHUB_REPOSITORY} --jq '.parent.full_name')
          run: |
            echo ${UPSTREAM_FULL_NAME}
            # gh api repos/${GITHUB_REPOSITORY} --jq '.parent.full_name'
            curl https://api.github.com/repos/touhoured/geph4-client | jq -r '.parent.full_name' | xargs echo full name: 
        - name: Get current time
          uses: josStorer/get-current-time@v2.0.2
          id: current-time
          with:
            format: YYYYMMDD
        - name: Use current time
          env:
            TIME: "${{ steps.current-time.outputs.time }}"
            R_TIME: "${{ steps.current-time.outputs.readableTime }}"
            F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
            YEAR: "${{ steps.current-time.outputs.year }}"
            DAY: "${{ steps.current-time.outputs.day }}"
          run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
        - name: Get tag
          id: tag
          uses: JinoArch/get-latest-tag@latest
        - name: Show tag
          env:
            latest: ${{ steps.tag.outputs.latestTag }}
            previous: ${{ steps.jinos.outputs.previousTag }}
          run: echo $latest $previous
