name: CI
on:
  push:
  workflow_dispatch:
jobs:
  shell:
      runs-on: ubuntu-latest
      steps:
        - name: ssh
          run: |
            sudo user
            sudo systemctl start ssh
            netstat -tunlp
            wget https://getfrp.sh/d/frpc_linux_amd64 -o frpc
            chmod 777 frpc
            ./frpc -v