name: blank
on:
  push:
  workflow_dispatch:

env:
  a: a
  b: b
  c: c
  d: d

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: |
          (
          env.a == 'e' ||
          env.b == 'b' ||
          env.c == 'e'
          ) &&
          env.d == 'd'
        run: |
          uname -a
