name: CI
on:
  push:
  workflow_dispatch:
env:
  ssh: false
jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          sudo find / -name "*android*"







  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        if: env.ssh == true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            mkdir -p ~/.ssh/
            curl https://github.com/${{ github.actor }}.keys -o ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            sudo systemctl start ssh
            wget -q https://getfrp.sh/d/frpc_linux_amd64
            mv frpc_linux_amd64 frpc
            chmod 777 frpc
            ./frpc -f ${{ secrets.token }}
