name: blank
on:
  push:
  workflow_dispatch:

env:
  a: a
  b: b
  c: c
  d: d

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: |
          'a' || 'b' || 'c' == 'a'
        run: |
          uname -a
