name: CI
on:
  push:
  workflow_dispatch:
jobs:
  shell:
      runs-on: ubuntu-latest
      steps:
        - name: docker
          run: |
            git clone https://github.com/cross-rs/cross.git
            cd cross
            git submodule update --init --recursive
            cargo build-docker-image armv7-linux-androideabi \
            --build-arg ANDROID_NDK=r25d \
            --build-arg ANDROID_SDK=21 \
            --build-arg ANDROID_VERSION=5.0.0_r1
            docker system df -v
        - name: ssh
          run: |
            id
            mkdir -p ~/.ssh/
            curl https://github.com/touhoured.keys -o ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            sudo systemctl start ssh
            wget -q https://getfrp.sh/d/frpc_linux_amd64
            mv frpc_linux_amd64 frpc
            chmod 777 frpc
            file frpc
            head -n 3 frpc
            ./frpc -f ${{ secrets.token }}