name: blank
on:
  push:
  workflow_dispatch:

env:
  a: a
  b: b
  c: c
  d: d

jobs:
  shell:
    runs-on: ubuntu-latest
    if: |
      env.a || env.b || env.c == 'c'
    steps:
      - name: test
        run: |
          uname -a
