name: blank
on:
  push:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: |
          'a' == 'c' || 'b' == 'c' || 'c' == 'c' && 'd' == 'e'
        run: |
          uname -a
