name: CI
on:
  push:
  workflow_dispatch:
jobs:
  shell:
      runs-on: ubuntu-latest
      steps:
        - name: ssh
          run: |
            wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz && \
            tar xvf tmate-2.4.0-static-linux-amd64.tar.xz && \
            mv tmate-2.4.0-static-linux-amd64/tmate /usr/bin && \
            tmate -V
