name: blank
on:
  push:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    if: |
      'a' == 'c' || 'b' == 'c' || 'c' == 'c' && 'd' == 'd'
    steps:
      - name: test
        run: |
          uname -a
