name: blank
on:
  push:
  workflow_dispatch:

env:
  a: n
  b: y
  c: n
  d: y

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: |
          (env.a || env.b || env.c || ) == 'y' &&
          env.d == 'y'
        run: |
          uname -a
