name: CI
on:
  push:
  workflow_dispatch:
jobs:
  shell:
      runs-on: ubuntu-latest
      steps:
        - name: ssh
          run: |
            id
            sudo systemctl start ssh
            docker run -d -p 22:22 --restart=always --pull=always --name=sakura1 natfrp/frpc -f ${{ secrets.token }}