name: CI
on:
  push:
  workflow_dispatch:
jobs:
  shell:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: README.md
          tag: test

