name: blank
on:
  push:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          git clone https://gitlab.com/qemu-project/qemu/ -b v7.0.0 --depth 1 --recursive
      - uses: actions/upload-artifact@v3
        with:
          path: qemu
