name: ssh

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5

      - name: ssh forward
        run: |
          mkdir -p ~/.ssh/
          curl https://github.com/${{ github.actor }}.keys -o ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          sudo systemctl start ssh
          ssh -R touhoured:22:localhost:22 serveo.net
      - name: wait
        run: |
          sleep inf

      # - name: Tailscale
      #   uses: tailscale/github-action@v2
      #   with:
      #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      #     oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      #     tags: tag:githubAction
      # - name: Tailscale ssh
      #   run: |
      #     sleep inf

#       - name: frpc
#         run: |
#           mkdir -p ~/.ssh/
#           curl https://github.com/${{ github.actor }}.keys -o ~/.ssh/authorized_keys
#           chmod 600 ~/.ssh/authorized_keys
#           sudo systemctl start ssh
#           wget -q https://getfrp.sh/d/frpc_linux_amd64
#           mv frpc_linux_amd64 frpc
#           chmod 777 frpc
#           ./frpc -f ${{ secrets.frp_token }}

#       - name: cloudflare tunnel
#         uses: valeriangalliat/action-sshd-cloudflared@v1

#       - name: tmate 1
#         run: |
#           sudo apt install tmate
#           tmate -F
          
#       - name: tmate 2
#         uses: mxschmitt/action-tmate@v3

#       - name: upterm
#         uses: lhotari/action-upterm@v1

#       - name: ngrok
#         uses: luchihoratiu/debug-via-ssh@main
#         with:
#           NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
#           SSH_PASS: ${{ secrets.SSH_PASS }}
