name: ssh

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            mkdir -p ~/.ssh/
            curl https://github.com/${{ github.actor }}.keys -o ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            sudo systemctl start ssh

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
